language: python
python:
  - "2.7_with_system_site_packages"
  - "3.4"
install: 
  - sudo apt-get install -qq python-numpy python-scipy
  - pip install patsy
  - pip install pandas
  - pip install scikit-learn
  - python setup.py build_ext --inplace

script: nosetests -s -v pyearth
